nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Access-Control-Request-Headers', 'Access-Control-Request-Method', 'Content-Type', 'Authorization', 'X-Custom-Auth']
        max_age: 3600
    paths:
        '^/': ~
